AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a Windows Server 2019 EC2 instance in Mumbai (ap-south-1)

Parameters:
  KeyName:
    Description: EC2 KeyPair for RDP access to the Windows instance
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: Must be a valid EC2 instance type.

Resources:

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  SSMPolicyForEC2:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EC2SSMAccessPolicy
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'ssm:SendCommand'
              - 'ssm:ListCommands'
              - 'ssm:DescribeInstanceInformation'
              - 'ssm:GetCommandInvocation'
              - 'ec2messages:*'
              - 'ssm:UpdateInstanceInformation'
              - 'cloudwatch:PutMetricData'
              - 'ec2:DescribeInstances'
            Resource: '*'

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: WindowsVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs 'ap-south-1']

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow RDP access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0  # Open for demo purposes

  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-019d9dc96246b7eb9  # Windows Server 2019 in ap-south-1
      IamInstanceProfile: !Ref MyInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnet
          GroupSet:
            - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: WindowsServer
      UserData: 
        Fn::Base64: !Sub |
          <powershell>
          # PowerShell script to be executed on Windows instance startup

          # Example: Installing IIS
          Install-WindowsFeature -Name Web-Server

          # Ensure SSM agent is installed and running
          if ((Get-Service -Name AmazonSSMAgent).Status -ne 'Running') {
              Start-Service AmazonSSMAgent
          }

          # Create a file for testing
          New-Item -Path "C:\temp\userdata-test.txt" -ItemType File -Force
          Set-Content -Path "C:\temp\userdata-test.txt" -Value "UserData script executed at $(Get-Date)"
          </powershell>

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref WindowsInstance

  PublicIP:
    Description: Public IP Address
    Value: !GetAtt WindowsInstance.PublicIp
