name: Deploy CloudFormation Template

on:
  push:
    branches: [ main ]  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # change to your region

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file ./template.yaml \
            --stack-name my-stack-name \
            --capabilities CAPABILITY_NAMED_IAM
